---
title: "Forest typing with Stem-maps in R"
author: "Justin Ziegler"
date: "October 15, 2018"
output: 
  html_document:
    excludes:
      after_body: footer.html
    includes:
      after_body: footer-disqus.html
---

<br>

>A few years ago, Kaggle held a competition to predict forest cover types using machine learning techniques. The data, taken from the Arapaho-Roosevelt National Forest here in Colorado and provided by the UCI Machine Learning Repository, contained a stack of rasters such as elevation, aspect, hillshade, distance to past fires, roads, and waterways. Competitors are supposed to use a subset of the current typology of forest cover to build and train machine learning algorithms which are then applied to a test set of forest cover types. This process works great for purposes such as forest planning or landscape ecology studies where 30-m resolution is sufficient.  

>But what if the ecological relationship of interest occurs at a much finer resolution and one would like to relate within-plot variability of some measure to an overstory-based typology. This post dives into using Spatstat to transform point-based observations to two-dimensional surfaces with categorical values.  

For this exercise, we will look at stem-map data used in Ziegler et al. (2017). In these stem-maps, I measured the locations and species of trees in seven 4-ha plots in Colorado, New Mexico, and Arizona. The data we will use comes from a single plot just outside of Red Feather Lake, Colorado which you can download in the link below. We will work with these data in R.  

install.packages('spatstat') #Download if you do not have

library(spatstat)
trees = read.table(url('https://dl.dropboxusercontent.com/s/35lqyl5ly0qmq9h/redfeather.txt?dl=0'),
                   header=T)
                   
Now let's create a ppp data type so that Spatstat can work with the data. We will also attribute marks to these points using 4-letter species codes.

treemap = ppp(trees$x_m, trees$y_m, c(0,200), c(0,200),
              unitname=c("meter","meter"), marks = trees$species)
plot(split(treemap),pch=19,cex=0.2)

The map split by species shows that quaking aspen (POTR) and Douglas-fir (PSME) are concentrated in a subset of the plot while ponderosa pine (PIPO) are almost everywhere.  

So we can already guess what forest types ought to appear from our analysis. To assign cover types, we will use the relrisk function. This function uses a kernel smoother to estimate a surface of likelihood of species occurrence using species' point densities. In this example, we will define the kernel's bandwidth and stipulate the resolution of the output image.  

speciesrisk = relrisk(treemap, sigma=2, dimyx = 50)
plot(speciesrisk)
covermap = im.apply(speciesrisk, which.max)
cover = levels(marks(treemap))
covermap = eval.im(cover[covermap])
plot(covermap, main="Cover type")

Overall, the results show that there are patches of quaking aspen and Douglas-fir in a sea of ponderosa pine.

<br>
<hr>
<br>

In the next step, we will further disaggregate cover types by size classes. For illustration, we will assume regeneration are those trees with diameter at breast height (dbh) less than 5 cm, mature trees have a dbh over 13 cm, and saplings are between the breakpoints. Here we will use ggplot2's (superior) plotting. Notice that in this example I used a wider bandwidth (sigma = 6) to gloss over fine-scale detail.

install.packages('ggplot2')
library(ggplot2)
trees$sizeclass = 'sapling'
trees$sizeclass[trees$dbh_cm<5] = 'regen'
trees$sizeclass[trees$dbh_cm>13] = 'tree'
trees$sizecoverclass = paste(trees$species,trees$sizeclass)

marks(treemap) = as.factor(trees$sizecoverclass)

classrisk = relrisk(treemap,sigma=6,dimyx=50)
covermap <- im.apply(classrisk, which.max)
cover <- levels(marks(treemap))
covermap <- as.data.frame(eval.im(cover[covermap]))

cols <- c('PIPO regen' ='#a50026', 'PIPO sapling'='#d73027',
          'PIPO tree'='#f46d43',   'POTR regen'='#006837',
          'POTR sapling'='#1a9850',    'POTR tree'='#66bd63',
          'PSME sapling'='#d9ef8b',    'PSME tree'='#ffffbf') 

ggplot(covermap,aes(x,y,fill=value))+geom_raster()+ scale_fill_manual(values = cols) +
theme_classic()

In this analysis, we see that most of the plot consists of ponderosa pine trees, but patches of seedlings and regeneration do exist. We can also note that most quaking aspen occur in regeneration patches. 

<br>
<hr>
<br>

One thing an ecologist might note is that larger trees might have a larger influence on their immediate environment than smaller trees. If so, it makes sense to weight the typology by tree size. Here we will use local basal area to determine which species are dominant.


trees$BA = trees$dbh_cm^2*.00007854
PIPOmap = with(trees[trees$species=='PIPO',], ppp(x_m, y_m, c(0, 200), c(0, 200), marks=BA))
POTRmap = with(trees[trees$species=='POTR',], ppp(x_m, y_m, c(0, 200), c(0, 200), marks=BA))
PSMEmap = with(trees[trees$species=='PSME',], ppp(x_m, y_m, c(0, 200), c(0, 200), marks=BA))

CoverbyBA = im.apply(list(
  Smooth(PIPOmap, 6, dimyx=50),
  Smooth(POTRmap, 6, dimyx=50),
  Smooth(PSMEmap, 6, dimyx=50)),
  which.max)

plot(eval.im(c('PIPO','POTR','PSME')[CoverbyBA]))

Woah! This doesn't look right. Douglas-fir shouldn't be the dominant cover type in half the plot.
The way the Smooth function works is that takes the marks of trees where the trees exist and then interpolates everywhere else. So it naturally can take a few large Douglas-fir trees and smoothes those data points over the whole plot. So here smoothing doesn't account for that fact that areas without Douglas-fir trees inherently have no Douglas-fir basal area.
One workaround would be weigh tree basal area by tree density. So now we will use the density function which is a way to interpolate tree density based on the spatially-varying frequency of mapped trees.

CoverbyBA = im.apply(list(
  Smooth(PIPOmap, 6, dimyx=50) * density(PIPOmap, 6, dimyx=50),
  Smooth(POTRmap, 6, dimyx=50) * density(POTRmap, 6, dimyx=50),
  Smooth(PSMEmap, 6, dimyx=50) * density(PSMEmap, 6, dimyx=50)),
  which.max)

plot(eval.im(c('PIPO','POTR','PSME')[CoverbyBA]))

Now this is better. It emphasizes the spatial dominance of ponderosa pine more so than our first typology. There is much less space assigned to quaking aspen in particular. That's because, according to our second typology, many patches of quaking aspen were just regeneration so they contributed less basal area than surrounding ponderosa pine. 

<br>
<hr>
<br>

What do you think? Can this approach be useful for categorizing intra-plot variation in your research? I'd like to hear your thoughts on using point-based spatial locations of trees, or any other discrete spatial events for that matter, to create raster images. 

<iframe width='100%' height='300' src='https://rdrr.io/snippets/embed/?code=print(%22wth%2C%20world!%22)' frameborder='0'></iframe>

[^1]: Footnote 
